/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cli.Model;
using cli.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cli.Test.Model
{
    /// <summary>
    ///  Class for testing AlertHistoryCommentsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlertHistoryCommentsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlertHistoryCommentsDto
        //private AlertHistoryCommentsDto instance;

        public AlertHistoryCommentsDtoTests()
        {
            // TODO uncomment below to create an instance of AlertHistoryCommentsDto
            //instance = new AlertHistoryCommentsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlertHistoryCommentsDto
        /// </summary>
        [Fact]
        public void AlertHistoryCommentsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlertHistoryCommentsDto
            //Assert.IsType<AlertHistoryCommentsDto>(instance);
        }

        /// <summary>
        /// Test the property 'AlertId'
        /// </summary>
        [Fact]
        public void AlertIdTest()
        {
            // TODO unit test for the property 'AlertId'
        }

        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Fact]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }

        /// <summary>
        /// Test the property 'Severities'
        /// </summary>
        [Fact]
        public void SeveritiesTest()
        {
            // TODO unit test for the property 'Severities'
        }
    }
}
