/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cli.Model;
using cli.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cli.Test.Model
{
    /// <summary>
    ///  Class for testing AuthenticatedUserDtoJSendSuccess
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthenticatedUserDtoJSendSuccessTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthenticatedUserDtoJSendSuccess
        //private AuthenticatedUserDtoJSendSuccess instance;

        public AuthenticatedUserDtoJSendSuccessTests()
        {
            // TODO uncomment below to create an instance of AuthenticatedUserDtoJSendSuccess
            //instance = new AuthenticatedUserDtoJSendSuccess();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthenticatedUserDtoJSendSuccess
        /// </summary>
        [Fact]
        public void AuthenticatedUserDtoJSendSuccessInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthenticatedUserDtoJSendSuccess
            //Assert.IsType<AuthenticatedUserDtoJSendSuccess>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
