/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cli.Model;
using cli.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cli.Test.Model
{
    /// <summary>
    ///  Class for testing AzureSqlDatabasesDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AzureSqlDatabasesDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AzureSqlDatabasesDto
        //private AzureSqlDatabasesDto instance;

        public AzureSqlDatabasesDtoTests()
        {
            // TODO uncomment below to create an instance of AzureSqlDatabasesDto
            //instance = new AzureSqlDatabasesDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AzureSqlDatabasesDto
        /// </summary>
        [Fact]
        public void AzureSqlDatabasesDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AzureSqlDatabasesDto
            //Assert.IsType<AzureSqlDatabasesDto>(instance);
        }

        /// <summary>
        /// Test the property 'AllDatabases'
        /// </summary>
        [Fact]
        public void AllDatabasesTest()
        {
            // TODO unit test for the property 'AllDatabases'
        }

        /// <summary>
        /// Test the property 'AutoDiscoveryEnabled'
        /// </summary>
        [Fact]
        public void AutoDiscoveryEnabledTest()
        {
            // TODO unit test for the property 'AutoDiscoveryEnabled'
        }
    }
}
