/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cli.Model;
using cli.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cli.Test.Model
{
    /// <summary>
    ///  Class for testing DatabasePrincipalType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DatabasePrincipalTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DatabasePrincipalType
        //private DatabasePrincipalType instance;

        public DatabasePrincipalTypeTests()
        {
            // TODO uncomment below to create an instance of DatabasePrincipalType
            //instance = new DatabasePrincipalType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DatabasePrincipalType
        /// </summary>
        [Fact]
        public void DatabasePrincipalTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" DatabasePrincipalType
            //Assert.IsType<DatabasePrincipalType>(instance);
        }
    }
}
