/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace cli.Test.Model;

/// <summary>
///     Class for testing EmailServerSettingsDto
/// </summary>
/// <remarks>
///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
///     Please update the test case below to test the model.
/// </remarks>
public class EmailServerSettingsDtoTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for EmailServerSettingsDto
    //private EmailServerSettingsDto instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    ///     Test an instance of EmailServerSettingsDto
    /// </summary>
    [Fact]
    public void EmailServerSettingsDtoInstanceTest()
    {
        // TODO uncomment below to test "IsType" EmailServerSettingsDto
        //Assert.IsType<EmailServerSettingsDto>(instance);
    }

    /// <summary>
    ///     Test the property 'Server'
    /// </summary>
    [Fact]
    public void ServerTest()
    {
        // TODO unit test for the property 'Server'
    }

    /// <summary>
    ///     Test the property 'Port'
    /// </summary>
    [Fact]
    public void PortTest()
    {
        // TODO unit test for the property 'Port'
    }

    /// <summary>
    ///     Test the property 'ConnectionSecurityMode'
    /// </summary>
    [Fact]
    public void ConnectionSecurityModeTest()
    {
        // TODO unit test for the property 'ConnectionSecurityMode'
    }

    /// <summary>
    ///     Test the property 'UseAuthentication'
    /// </summary>
    [Fact]
    public void UseAuthenticationTest()
    {
        // TODO unit test for the property 'UseAuthentication'
    }

    /// <summary>
    ///     Test the property 'Username'
    /// </summary>
    [Fact]
    public void UsernameTest()
    {
        // TODO unit test for the property 'Username'
    }

    /// <summary>
    ///     Test the property 'Password'
    /// </summary>
    [Fact]
    public void PasswordTest()
    {
        // TODO unit test for the property 'Password'
    }

    /// <summary>
    ///     Test the property 'EmailFrom'
    /// </summary>
    [Fact]
    public void EmailFromTest()
    {
        // TODO unit test for the property 'EmailFrom'
    }

    /// <summary>
    ///     Test the property 'IgnoreSslErrors'
    /// </summary>
    [Fact]
    public void IgnoreSslErrorsTest()
    {
        // TODO unit test for the property 'IgnoreSslErrors'
    }

    /// <summary>
    ///     Test the property 'HasDecryptionError'
    /// </summary>
    [Fact]
    public void HasDecryptionErrorTest()
    {
        // TODO unit test for the property 'HasDecryptionError'
    }

    /// <summary>
    ///     Test the property 'SecureConnectionSecurity'
    /// </summary>
    [Fact]
    public void SecureConnectionSecurityTest()
    {
        // TODO unit test for the property 'SecureConnectionSecurity'
    }
}