/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace cli.Test.Model;

/// <summary>
///     Class for testing MachineConfiguration
/// </summary>
/// <remarks>
///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
///     Please update the test case below to test the model.
/// </remarks>
public class MachineConfigurationTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for MachineConfiguration
    //private MachineConfiguration instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    ///     Test an instance of MachineConfiguration
    /// </summary>
    [Fact]
    public void MachineConfigurationInstanceTest()
    {
        // TODO uncomment below to test "IsType" MachineConfiguration
        //Assert.IsType<MachineConfiguration>(instance);
    }

    /// <summary>
    ///     Test the property 'WindowsConnectionProperties'
    /// </summary>
    [Fact]
    public void WindowsConnectionPropertiesTest()
    {
        // TODO unit test for the property 'WindowsConnectionProperties'
    }

    /// <summary>
    ///     Test the property 'UseBaseMonitorServiceAccount'
    /// </summary>
    [Fact]
    public void UseBaseMonitorServiceAccountTest()
    {
        // TODO unit test for the property 'UseBaseMonitorServiceAccount'
    }

    /// <summary>
    ///     Test the property 'Credentials'
    /// </summary>
    [Fact]
    public void CredentialsTest()
    {
        // TODO unit test for the property 'Credentials'
    }

    /// <summary>
    ///     Test the property 'SshAuthenticationType'
    /// </summary>
    [Fact]
    public void SshAuthenticationTypeTest()
    {
        // TODO unit test for the property 'SshAuthenticationType'
    }

    /// <summary>
    ///     Test the property 'SshPrivateKeyId'
    /// </summary>
    [Fact]
    public void SshPrivateKeyIdTest()
    {
        // TODO unit test for the property 'SshPrivateKeyId'
    }
}