/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cli.Model;
using cli.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cli.Test.Model
{
    /// <summary>
    ///  Class for testing PostgresQueryRecommendationType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostgresQueryRecommendationTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostgresQueryRecommendationType
        //private PostgresQueryRecommendationType instance;

        public PostgresQueryRecommendationTypeTests()
        {
            // TODO uncomment below to create an instance of PostgresQueryRecommendationType
            //instance = new PostgresQueryRecommendationType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostgresQueryRecommendationType
        /// </summary>
        [Fact]
        public void PostgresQueryRecommendationTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostgresQueryRecommendationType
            //Assert.IsType<PostgresQueryRecommendationType>(instance);
        }
    }
}
