/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace cli.Test.Model;

/// <summary>
///     Class for testing UserServerRolesDto
/// </summary>
/// <remarks>
///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
///     Please update the test case below to test the model.
/// </remarks>
public class UserServerRolesDtoTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for UserServerRolesDto
    //private UserServerRolesDto instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    ///     Test an instance of UserServerRolesDto
    /// </summary>
    [Fact]
    public void UserServerRolesDtoInstanceTest()
    {
        // TODO uncomment below to test "IsType" UserServerRolesDto
        //Assert.IsType<UserServerRolesDto>(instance);
    }

    /// <summary>
    ///     Test the property 'Name'
    /// </summary>
    [Fact]
    public void NameTest()
    {
        // TODO unit test for the property 'Name'
    }

    /// <summary>
    ///     Test the property 'AccountName'
    /// </summary>
    [Fact]
    public void AccountNameTest()
    {
        // TODO unit test for the property 'AccountName'
    }

    /// <summary>
    ///     Test the property 'Sid'
    /// </summary>
    [Fact]
    public void SidTest()
    {
        // TODO unit test for the property 'Sid'
    }

    /// <summary>
    ///     Test the property 'Roles'
    /// </summary>
    [Fact]
    public void RolesTest()
    {
        // TODO unit test for the property 'Roles'
    }

    /// <summary>
    ///     Test the property 'CreatedDate'
    /// </summary>
    [Fact]
    public void CreatedDateTest()
    {
        // TODO unit test for the property 'CreatedDate'
    }
}