/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using cli.Client;
using cli.Model;

namespace cli.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAzureManagedInstanceAlertSettingsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatch(string serverName, long alertTypeId, string baseMonitorName, string? body = default(string?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatchWithHttpInfo(string serverName, long alertTypeId, string baseMonitorName, string? body = default(string?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGet(string serverName, long alertTypeId, string baseMonitorName, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGetWithHttpInfo(string serverName, long alertTypeId, string baseMonitorName, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="alertNotificationSettingsDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatch(string serverName, long alertTypeId, string baseMonitorName, AlertNotificationSettingsDto? alertNotificationSettingsDto = default(AlertNotificationSettingsDto?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="alertNotificationSettingsDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatchWithHttpInfo(string serverName, long alertTypeId, string baseMonitorName, AlertNotificationSettingsDto? alertNotificationSettingsDto = default(AlertNotificationSettingsDto?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatch(string serverName, long alertTypeId, string baseMonitorName, Hashtable? requestBody = default(Hashtable?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatchWithHttpInfo(string serverName, long alertTypeId, string baseMonitorName, Hashtable? requestBody = default(Hashtable?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatch(string serverName, long alertTypeId, string baseMonitorName, int? body = default(int?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatchWithHttpInfo(string serverName, long alertTypeId, string baseMonitorName, int? body = default(int?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAzureManagedInstanceAlertSettingsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatchAsync(string serverName, long alertTypeId, string baseMonitorName, string? body = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatchWithHttpInfoAsync(string serverName, long alertTypeId, string baseMonitorName, string? body = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGetAsync(string serverName, long alertTypeId, string baseMonitorName, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGetWithHttpInfoAsync(string serverName, long alertTypeId, string baseMonitorName, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="alertNotificationSettingsDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatchAsync(string serverName, long alertTypeId, string baseMonitorName, AlertNotificationSettingsDto? alertNotificationSettingsDto = default(AlertNotificationSettingsDto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="alertNotificationSettingsDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatchWithHttpInfoAsync(string serverName, long alertTypeId, string baseMonitorName, AlertNotificationSettingsDto? alertNotificationSettingsDto = default(AlertNotificationSettingsDto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatchAsync(string serverName, long alertTypeId, string baseMonitorName, Hashtable? requestBody = default(Hashtable?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatchWithHttpInfoAsync(string serverName, long alertTypeId, string baseMonitorName, Hashtable? requestBody = default(Hashtable?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatchAsync(string serverName, long alertTypeId, string baseMonitorName, int? body = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatchWithHttpInfoAsync(string serverName, long alertTypeId, string baseMonitorName, int? body = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAzureManagedInstanceAlertSettingsApi : IAzureManagedInstanceAlertSettingsApiSync, IAzureManagedInstanceAlertSettingsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AzureManagedInstanceAlertSettingsApi : IAzureManagedInstanceAlertSettingsApi
    {
        private cli.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AzureManagedInstanceAlertSettingsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AzureManagedInstanceAlertSettingsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AzureManagedInstanceAlertSettingsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AzureManagedInstanceAlertSettingsApi(string basePath)
        {
            this.Configuration = cli.Client.Configuration.MergeConfigurations(
                cli.Client.GlobalConfiguration.Instance,
                new cli.Client.Configuration { BasePath = basePath }
            );
            this.Client = new cli.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new cli.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = cli.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AzureManagedInstanceAlertSettingsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AzureManagedInstanceAlertSettingsApi(cli.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = cli.Client.Configuration.MergeConfigurations(
                cli.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new cli.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new cli.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = cli.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AzureManagedInstanceAlertSettingsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AzureManagedInstanceAlertSettingsApi(cli.Client.ISynchronousClient client, cli.Client.IAsynchronousClient asyncClient, cli.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = cli.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public cli.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public cli.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public cli.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public cli.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatch(string serverName, long alertTypeId, string baseMonitorName, string? body = default(string?), int operationIndex = 0)
        {
            ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatchWithHttpInfo(serverName, alertTypeId, baseMonitorName, body);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public cli.Client.ApiResponse<Object> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatchWithHttpInfo(string serverName, long alertTypeId, string baseMonitorName, string? body = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'serverName' is set
            if (serverName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'serverName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatch");
            }

            // verify the required parameter 'baseMonitorName' is set
            if (baseMonitorName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'baseMonitorName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatch");
            }

            cli.Client.RequestOptions localVarRequestOptions = new cli.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = cli.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = cli.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("serverName", cli.Client.ClientUtils.ParameterToString(serverName)); // path parameter
            localVarRequestOptions.PathParameters.Add("alertTypeId", cli.Client.ClientUtils.ParameterToString(alertTypeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("baseMonitorName", cli.Client.ClientUtils.ParameterToString(baseMonitorName)); // path parameter
            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "AzureManagedInstanceAlertSettingsApi.ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatch";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/api/basemonitors/{baseMonitorName}/azuremanagedinstances/{serverName}/alertsettings/{alertTypeId}/comments", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatchAsync(string serverName, long alertTypeId, string baseMonitorName, string? body = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatchWithHttpInfoAsync(serverName, alertTypeId, baseMonitorName, body, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<cli.Client.ApiResponse<Object>> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatchWithHttpInfoAsync(string serverName, long alertTypeId, string baseMonitorName, string? body = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'serverName' is set
            if (serverName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'serverName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatch");
            }

            // verify the required parameter 'baseMonitorName' is set
            if (baseMonitorName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'baseMonitorName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatch");
            }


            cli.Client.RequestOptions localVarRequestOptions = new cli.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = cli.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = cli.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("serverName", cli.Client.ClientUtils.ParameterToString(serverName)); // path parameter
            localVarRequestOptions.PathParameters.Add("alertTypeId", cli.Client.ClientUtils.ParameterToString(alertTypeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("baseMonitorName", cli.Client.ClientUtils.ParameterToString(baseMonitorName)); // path parameter
            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "AzureManagedInstanceAlertSettingsApi.ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatch";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<Object>("/api/basemonitors/{baseMonitorName}/azuremanagedinstances/{serverName}/alertsettings/{alertTypeId}/comments", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdCommentsPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGet(string serverName, long alertTypeId, string baseMonitorName, int operationIndex = 0)
        {
            ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGetWithHttpInfo(serverName, alertTypeId, baseMonitorName);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public cli.Client.ApiResponse<Object> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGetWithHttpInfo(string serverName, long alertTypeId, string baseMonitorName, int operationIndex = 0)
        {
            // verify the required parameter 'serverName' is set
            if (serverName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'serverName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGet");
            }

            // verify the required parameter 'baseMonitorName' is set
            if (baseMonitorName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'baseMonitorName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGet");
            }

            cli.Client.RequestOptions localVarRequestOptions = new cli.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = cli.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = cli.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("serverName", cli.Client.ClientUtils.ParameterToString(serverName)); // path parameter
            localVarRequestOptions.PathParameters.Add("alertTypeId", cli.Client.ClientUtils.ParameterToString(alertTypeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("baseMonitorName", cli.Client.ClientUtils.ParameterToString(baseMonitorName)); // path parameter

            localVarRequestOptions.Operation = "AzureManagedInstanceAlertSettingsApi.ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/api/basemonitors/{baseMonitorName}/azuremanagedinstances/{serverName}/alertsettings/{alertTypeId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGetAsync(string serverName, long alertTypeId, string baseMonitorName, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGetWithHttpInfoAsync(serverName, alertTypeId, baseMonitorName, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<cli.Client.ApiResponse<Object>> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGetWithHttpInfoAsync(string serverName, long alertTypeId, string baseMonitorName, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'serverName' is set
            if (serverName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'serverName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGet");
            }

            // verify the required parameter 'baseMonitorName' is set
            if (baseMonitorName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'baseMonitorName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGet");
            }


            cli.Client.RequestOptions localVarRequestOptions = new cli.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = cli.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = cli.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("serverName", cli.Client.ClientUtils.ParameterToString(serverName)); // path parameter
            localVarRequestOptions.PathParameters.Add("alertTypeId", cli.Client.ClientUtils.ParameterToString(alertTypeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("baseMonitorName", cli.Client.ClientUtils.ParameterToString(baseMonitorName)); // path parameter

            localVarRequestOptions.Operation = "AzureManagedInstanceAlertSettingsApi.ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/api/basemonitors/{baseMonitorName}/azuremanagedinstances/{serverName}/alertsettings/{alertTypeId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="alertNotificationSettingsDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatch(string serverName, long alertTypeId, string baseMonitorName, AlertNotificationSettingsDto? alertNotificationSettingsDto = default(AlertNotificationSettingsDto?), int operationIndex = 0)
        {
            ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatchWithHttpInfo(serverName, alertTypeId, baseMonitorName, alertNotificationSettingsDto);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="alertNotificationSettingsDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public cli.Client.ApiResponse<Object> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatchWithHttpInfo(string serverName, long alertTypeId, string baseMonitorName, AlertNotificationSettingsDto? alertNotificationSettingsDto = default(AlertNotificationSettingsDto?), int operationIndex = 0)
        {
            // verify the required parameter 'serverName' is set
            if (serverName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'serverName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatch");
            }

            // verify the required parameter 'baseMonitorName' is set
            if (baseMonitorName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'baseMonitorName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatch");
            }

            cli.Client.RequestOptions localVarRequestOptions = new cli.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = cli.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = cli.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("serverName", cli.Client.ClientUtils.ParameterToString(serverName)); // path parameter
            localVarRequestOptions.PathParameters.Add("alertTypeId", cli.Client.ClientUtils.ParameterToString(alertTypeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("baseMonitorName", cli.Client.ClientUtils.ParameterToString(baseMonitorName)); // path parameter
            localVarRequestOptions.Data = alertNotificationSettingsDto;

            localVarRequestOptions.Operation = "AzureManagedInstanceAlertSettingsApi.ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatch";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/api/basemonitors/{baseMonitorName}/azuremanagedinstances/{serverName}/alertsettings/{alertTypeId}/notificationsettings", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="alertNotificationSettingsDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatchAsync(string serverName, long alertTypeId, string baseMonitorName, AlertNotificationSettingsDto? alertNotificationSettingsDto = default(AlertNotificationSettingsDto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatchWithHttpInfoAsync(serverName, alertTypeId, baseMonitorName, alertNotificationSettingsDto, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="alertNotificationSettingsDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<cli.Client.ApiResponse<Object>> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatchWithHttpInfoAsync(string serverName, long alertTypeId, string baseMonitorName, AlertNotificationSettingsDto? alertNotificationSettingsDto = default(AlertNotificationSettingsDto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'serverName' is set
            if (serverName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'serverName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatch");
            }

            // verify the required parameter 'baseMonitorName' is set
            if (baseMonitorName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'baseMonitorName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatch");
            }


            cli.Client.RequestOptions localVarRequestOptions = new cli.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = cli.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = cli.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("serverName", cli.Client.ClientUtils.ParameterToString(serverName)); // path parameter
            localVarRequestOptions.PathParameters.Add("alertTypeId", cli.Client.ClientUtils.ParameterToString(alertTypeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("baseMonitorName", cli.Client.ClientUtils.ParameterToString(baseMonitorName)); // path parameter
            localVarRequestOptions.Data = alertNotificationSettingsDto;

            localVarRequestOptions.Operation = "AzureManagedInstanceAlertSettingsApi.ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatch";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<Object>("/api/basemonitors/{baseMonitorName}/azuremanagedinstances/{serverName}/alertsettings/{alertTypeId}/notificationsettings", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdNotificationsettingsPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatch(string serverName, long alertTypeId, string baseMonitorName, Hashtable? requestBody = default(Hashtable?), int operationIndex = 0)
        {
            ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatchWithHttpInfo(serverName, alertTypeId, baseMonitorName, requestBody);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public cli.Client.ApiResponse<Object> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatchWithHttpInfo(string serverName, long alertTypeId, string baseMonitorName, Hashtable? requestBody = default(Hashtable?), int operationIndex = 0)
        {
            // verify the required parameter 'serverName' is set
            if (serverName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'serverName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatch");
            }

            // verify the required parameter 'baseMonitorName' is set
            if (baseMonitorName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'baseMonitorName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatch");
            }

            cli.Client.RequestOptions localVarRequestOptions = new cli.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = cli.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = cli.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("serverName", cli.Client.ClientUtils.ParameterToString(serverName)); // path parameter
            localVarRequestOptions.PathParameters.Add("alertTypeId", cli.Client.ClientUtils.ParameterToString(alertTypeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("baseMonitorName", cli.Client.ClientUtils.ParameterToString(baseMonitorName)); // path parameter
            localVarRequestOptions.Data = requestBody;

            localVarRequestOptions.Operation = "AzureManagedInstanceAlertSettingsApi.ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatch";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/api/basemonitors/{baseMonitorName}/azuremanagedinstances/{serverName}/alertsettings/{alertTypeId}/specificsettings", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatchAsync(string serverName, long alertTypeId, string baseMonitorName, Hashtable? requestBody = default(Hashtable?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatchWithHttpInfoAsync(serverName, alertTypeId, baseMonitorName, requestBody, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<cli.Client.ApiResponse<Object>> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatchWithHttpInfoAsync(string serverName, long alertTypeId, string baseMonitorName, Hashtable? requestBody = default(Hashtable?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'serverName' is set
            if (serverName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'serverName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatch");
            }

            // verify the required parameter 'baseMonitorName' is set
            if (baseMonitorName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'baseMonitorName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatch");
            }


            cli.Client.RequestOptions localVarRequestOptions = new cli.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = cli.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = cli.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("serverName", cli.Client.ClientUtils.ParameterToString(serverName)); // path parameter
            localVarRequestOptions.PathParameters.Add("alertTypeId", cli.Client.ClientUtils.ParameterToString(alertTypeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("baseMonitorName", cli.Client.ClientUtils.ParameterToString(baseMonitorName)); // path parameter
            localVarRequestOptions.Data = requestBody;

            localVarRequestOptions.Operation = "AzureManagedInstanceAlertSettingsApi.ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatch";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<Object>("/api/basemonitors/{baseMonitorName}/azuremanagedinstances/{serverName}/alertsettings/{alertTypeId}/specificsettings", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdSpecificsettingsPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatch(string serverName, long alertTypeId, string baseMonitorName, int? body = default(int?), int operationIndex = 0)
        {
            ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatchWithHttpInfo(serverName, alertTypeId, baseMonitorName, body);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public cli.Client.ApiResponse<Object> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatchWithHttpInfo(string serverName, long alertTypeId, string baseMonitorName, int? body = default(int?), int operationIndex = 0)
        {
            // verify the required parameter 'serverName' is set
            if (serverName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'serverName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatch");
            }

            // verify the required parameter 'baseMonitorName' is set
            if (baseMonitorName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'baseMonitorName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatch");
            }

            cli.Client.RequestOptions localVarRequestOptions = new cli.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = cli.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = cli.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("serverName", cli.Client.ClientUtils.ParameterToString(serverName)); // path parameter
            localVarRequestOptions.PathParameters.Add("alertTypeId", cli.Client.ClientUtils.ParameterToString(alertTypeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("baseMonitorName", cli.Client.ClientUtils.ParameterToString(baseMonitorName)); // path parameter
            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "AzureManagedInstanceAlertSettingsApi.ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatch";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/api/basemonitors/{baseMonitorName}/azuremanagedinstances/{serverName}/alertsettings/{alertTypeId}/status", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatchAsync(string serverName, long alertTypeId, string baseMonitorName, int? body = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatchWithHttpInfoAsync(serverName, alertTypeId, baseMonitorName, body, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="cli.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serverName"></param>
        /// <param name="alertTypeId"></param>
        /// <param name="baseMonitorName"></param>
        /// <param name="body"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<cli.Client.ApiResponse<Object>> ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatchWithHttpInfoAsync(string serverName, long alertTypeId, string baseMonitorName, int? body = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'serverName' is set
            if (serverName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'serverName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatch");
            }

            // verify the required parameter 'baseMonitorName' is set
            if (baseMonitorName == null)
            {
                throw new cli.Client.ApiException(400, "Missing required parameter 'baseMonitorName' when calling AzureManagedInstanceAlertSettingsApi->ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatch");
            }


            cli.Client.RequestOptions localVarRequestOptions = new cli.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = cli.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = cli.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("serverName", cli.Client.ClientUtils.ParameterToString(serverName)); // path parameter
            localVarRequestOptions.PathParameters.Add("alertTypeId", cli.Client.ClientUtils.ParameterToString(alertTypeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("baseMonitorName", cli.Client.ClientUtils.ParameterToString(baseMonitorName)); // path parameter
            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "AzureManagedInstanceAlertSettingsApi.ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatch";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<Object>("/api/basemonitors/{baseMonitorName}/azuremanagedinstances/{serverName}/alertsettings/{alertTypeId}/status", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiBasemonitorsBaseMonitorNameAzuremanagedinstancesServerNameAlertsettingsAlertTypeIdStatusPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
