/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using cli.Client;
using cli.Api;
// uncomment below to import models
//using cli.Model;

namespace cli.Test.Api
{
    /// <summary>
    ///  Class for testing ClusterAlertSettingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ClusterAlertSettingsApiTests : IDisposable
    {
        private ClusterAlertSettingsApi instance;

        public ClusterAlertSettingsApiTests()
        {
            instance = new ClusterAlertSettingsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClusterAlertSettingsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ClusterAlertSettingsApi
            //Assert.IsType<ClusterAlertSettingsApi>(instance);
        }

        /// <summary>
        /// Test ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdCommentsPatch
        /// </summary>
        [Fact]
        public void ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdCommentsPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clusterName = null;
            //long alertTypeId = null;
            //string baseMonitorName = null;
            //string? body = null;
            //instance.ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdCommentsPatch(clusterName, alertTypeId, baseMonitorName, body);
        }

        /// <summary>
        /// Test ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdGet
        /// </summary>
        [Fact]
        public void ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clusterName = null;
            //long alertTypeId = null;
            //string baseMonitorName = null;
            //var response = instance.ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdGet(clusterName, alertTypeId, baseMonitorName);
            //Assert.IsType<AlertSettingsDto>(response);
        }

        /// <summary>
        /// Test ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdNotificationsettingsPatch
        /// </summary>
        [Fact]
        public void ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdNotificationsettingsPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clusterName = null;
            //long alertTypeId = null;
            //string baseMonitorName = null;
            //AlertNotificationSettingsDto? alertNotificationSettingsDto = null;
            //instance.ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdNotificationsettingsPatch(clusterName, alertTypeId, baseMonitorName, alertNotificationSettingsDto);
        }

        /// <summary>
        /// Test ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdSpecificsettingsPatch
        /// </summary>
        [Fact]
        public void ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdSpecificsettingsPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clusterName = null;
            //long alertTypeId = null;
            //string baseMonitorName = null;
            //Hashtable? requestBody = null;
            //instance.ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdSpecificsettingsPatch(clusterName, alertTypeId, baseMonitorName, requestBody);
        }

        /// <summary>
        /// Test ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdStatusPatch
        /// </summary>
        [Fact]
        public void ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdStatusPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clusterName = null;
            //long alertTypeId = null;
            //string baseMonitorName = null;
            //int? body = null;
            //instance.ApiBasemonitorsBaseMonitorNameClustersClusterNameAlertsettingsAlertTypeIdStatusPatch(clusterName, alertTypeId, baseMonitorName, body);
        }
    }
}
