/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using cli.Api;
using Xunit;

// uncomment below to import models
//using cli.Model;

namespace cli.Test.Api;

/// <summary>
///     Class for testing ConfigureLoggingApiApi
/// </summary>
/// <remarks>
///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
///     Please update the test case below to test the API endpoint.
/// </remarks>
public class ConfigureLoggingApiApiTests : IDisposable
{
    private ConfigureLoggingApiApi instance;

    public ConfigureLoggingApiApiTests()
    {
        instance = new ConfigureLoggingApiApi();
    }

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    ///     Test an instance of ConfigureLoggingApiApi
    /// </summary>
    [Fact]
    public void InstanceTest()
    {
        // TODO uncomment below to test 'IsType' ConfigureLoggingApiApi
        //Assert.IsType<ConfigureLoggingApiApi>(instance);
    }

    /// <summary>
    ///     Test ApiBasemonitorsBaseMonitorNameConfigurationLoggingPost
    /// </summary>
    [Fact]
    public void ApiBasemonitorsBaseMonitorNameConfigurationLoggingPostTest()
    {
        // TODO uncomment below to test the method and replace null with proper value
        //string baseMonitorName = null;
        //LogLevelSwitchParamsDto? logLevelSwitchParamsDto = null;
        //var response = instance.ApiBasemonitorsBaseMonitorNameConfigurationLoggingPost(baseMonitorName, logLevelSwitchParamsDto);
        //Assert.IsType<JSendSuccess>(response);
    }

    /// <summary>
    ///     Test ApiConfigurationLoggingPerformancePost
    /// </summary>
    [Fact]
    public void ApiConfigurationLoggingPerformancePostTest()
    {
        // TODO uncomment below to test the method and replace null with proper value
        //int? enabledSeconds = null;
        //var response = instance.ApiConfigurationLoggingPerformancePost(enabledSeconds);
        //Assert.IsType<JSendSuccess>(response);
    }

    /// <summary>
    ///     Test ApiConfigurationLoggingPost
    /// </summary>
    [Fact]
    public void ApiConfigurationLoggingPostTest()
    {
        // TODO uncomment below to test the method and replace null with proper value
        //LogLevelSwitchParamsDto? logLevelSwitchParamsDto = null;
        //var response = instance.ApiConfigurationLoggingPost(logLevelSwitchParamsDto);
        //Assert.IsType<JSendSuccess>(response);
    }
}