/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using cli.Client;
using cli.Api;
// uncomment below to import models
//using cli.Model;

namespace cli.Test.Api
{
    /// <summary>
    ///  Class for testing DiscoveryApiApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DiscoveryApiApiTests : IDisposable
    {
        private DiscoveryApiApi instance;

        public DiscoveryApiApiTests()
        {
            instance = new DiscoveryApiApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DiscoveryApiApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DiscoveryApiApi
            //Assert.IsType<DiscoveryApiApi>(instance);
        }

        /// <summary>
        /// Test CancelDiscovery
        /// </summary>
        [Fact]
        public void CancelDiscoveryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string baseMonitorName = null;
            //var response = instance.CancelDiscovery(baseMonitorName);
            //Assert.IsType<UnitJSendSuccess>(response);
        }

        /// <summary>
        /// Test DownloadDiscovery
        /// </summary>
        [Fact]
        public void DownloadDiscoveryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string baseMonitorName = null;
            //instance.DownloadDiscovery(baseMonitorName);
        }

        /// <summary>
        /// Test GetAzureDetectionResult
        /// </summary>
        [Fact]
        public void GetAzureDetectionResultTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string baseMonitorName = null;
            //AzureDetectionOptionsDto? azureDetectionOptionsDto = null;
            //instance.GetAzureDetectionResult(baseMonitorName, azureDetectionOptionsDto);
        }

        /// <summary>
        /// Test GetDiscoveryResult
        /// </summary>
        [Fact]
        public void GetDiscoveryResultTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string baseMonitorName = null;
            //var response = instance.GetDiscoveryResult(baseMonitorName);
            //Assert.IsType<DiscoveryResultDtoJSendSuccess>(response);
        }

        /// <summary>
        /// Test GetRdsDetectionResult
        /// </summary>
        [Fact]
        public void GetRdsDetectionResultTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string baseMonitorName = null;
            //RdsDetectionOptionsDto? rdsDetectionOptionsDto = null;
            //instance.GetRdsDetectionResult(baseMonitorName, rdsDetectionOptionsDto);
        }

        /// <summary>
        /// Test StartDiscovery
        /// </summary>
        [Fact]
        public void StartDiscoveryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string baseMonitorName = null;
            //DiscoveryOptionsDto? discoveryOptionsDto = null;
            //var response = instance.StartDiscovery(baseMonitorName, discoveryOptionsDto);
            //Assert.IsType<UnitJSendSuccess>(response);
        }
    }
}
