/*
 * Redgate Monitor API - internal - for dev use only
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 14.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace cli.Model;

/// <summary>
///     BlockedBaseMonitorsDto
/// </summary>
[DataContract(Name = "BlockedBaseMonitorsDto")]
public class BlockedBaseMonitorsDto : IValidatableObject
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="BlockedBaseMonitorsDto" /> class.
    /// </summary>
    /// <param name="areBlockedBaseMonitors">areBlockedBaseMonitors.</param>
    /// <param name="listOfBlockedBms">listOfBlockedBms.</param>
    public BlockedBaseMonitorsDto(bool areBlockedBaseMonitors = default, string listOfBlockedBms = default)
    {
        AreBlockedBaseMonitors = areBlockedBaseMonitors;
        ListOfBlockedBms = listOfBlockedBms;
    }

    /// <summary>
    ///     Gets or Sets AreBlockedBaseMonitors
    /// </summary>
    [DataMember(Name = "areBlockedBaseMonitors", EmitDefaultValue = true)]
    public bool AreBlockedBaseMonitors { get; set; }

    /// <summary>
    ///     Gets or Sets ListOfBlockedBms
    /// </summary>
    [DataMember(Name = "listOfBlockedBms", EmitDefaultValue = true)]
    public string ListOfBlockedBms { get; set; }

    /// <summary>
    ///     To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class BlockedBaseMonitorsDto {\n");
        sb.Append("  AreBlockedBaseMonitors: ").Append(AreBlockedBaseMonitors).Append("\n");
        sb.Append("  ListOfBlockedBms: ").Append(ListOfBlockedBms).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}